#!/bin/bash
set -x

echo "Running docker nx-libs build script ..."

script_error="##SCRIPT ERROR##"

check_error() {

  if [ $? -eq 0 ]; then
    echo $1 " check_error success!"
  else
    echo $1 " check_error error!"
    echo $script_errror
    exit 1
  fi
}

docker image inspect lilitun/nx-libs-build:1.0 &>/dev/null
if [ $? -ne 0 ]; then
    docker build -t lilitun/nx-libs-build:1.0 docker-build
    check_error "docker build -t lilitun/nx-libs-build:1.0 docker-build"
fi

docker run -ti --rm -v $PWD:/root/src lilitun/nx-libs-build:1.0
check_error "docker run -ti --rm -v $PWD:/root/src lilitun/nx-libs-build:1.0"

echo "LiliTun remote control build completed successfully!!"

docker image inspect lilitun/nx-libs-run:1.0 &>/dev/null
if [ $? -eq 0 ]; then
    ID=$(docker ps -q --filter ancestor=lilitun/nx-libs-run:1.0)

    if [ "$ID" != "" ]; then
        docker stop $ID
    fi

    docker image rm -f lilitun/nx-libs-run:1.0
fi

cp -R release docker-run
docker build -t lilitun/nx-libs-run:1.0 docker-run
check_error "docker build -t lilitun/nx-libs-run:1.0 docker-run"

rm -rf docker-run/release
